# Generated by Django 2.0 on 2018-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_sz', models.CharField(max_length=2)),
                ('highInit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('setDate', models.DateField(auto_now_add=True)),
                ('highest', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
