# Generated by Django 2.0 on 2018-01-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xjgl', '0002_auto_20180114_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhg',
            name='highTodayInit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
