# Generated by Django 2.0 on 2018-01-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xjgl', '0003_nhg_hightodayinit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhg',
            name='row_sz',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
