# Generated by Django 2.0 on 2018-01-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xjgl', '0004_auto_20180114_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhg',
            name='highInit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nhg',
            name='highTodayInit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nhg',
            name='highest',
            field=models.FloatField(),
        ),
    ]
