# Generated by Django 2.0 on 2018-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('runFlag', models.BooleanField(default=0)),
                ('webSite', models.CharField(max_length=100)),
                ('timePeriod', models.CharField(max_length=100)),
                ('timeRelax', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
