# Generated by Django 2.0 on 2018-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rask',
            name='weekday',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
